@startuml
'https://plantuml.com/use-case-diagram
left to right direction

:Administrador: --> (Crear Colección)
:Administrador: --> (Importar hechos desde CSV)
:Administrador: --> (Aceptar o Rechazar solicitud de eliminacion)

:Visualizadora: --> (Navegar Colección)
(Navegar Colección) <.. (Aplicar Filtros) : <<extend>>

:Contribuyente: --> (Solicitar eliminacion de un hecho)


(Solicitar eliminacion de un hecho) ..> (Aceptar o Rechazar solicitud de eliminacion) : <<extend>>


(Crear Colección) ..> (Ïniciar Sesion) : <<include>>
(Importar hechos desde CSV) ..> (Ïniciar Sesion) : <<include>>
(Aceptar o Rechazar solicitud de eliminacion) ..> (Ïniciar Sesion) : <<include>>









@enduml